name: CI

on:
  push:
  pull_request:
  merge_group:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --locked -- -D warnings

  fmt:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
         lfs: true
    - uses: dtolnay/rust-toolchain@stable
    - name: Build shim
      run: cargo build --locked
    - name: Test shim
      run: |
          # runc-shim::cgroup::test_add_cgroup needs root permission to set cgroup
          mkdir -p /tmp/dummy-xdr
          sudo -E $(command -v cargo) test
          sudo -E $(command -v cargo) test --all-features
          sudo -E $(command -v cargo) test -p runh --lib
